[build]
command = "pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .."

[deploy]
startCommand = "uvicorn backend.server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
